### ISSUE TITLE
Export png or widget

### ISSUE THREAD

**Issue by jfear** [igvteam/igv-jupyter#1]
This is an interesting project. For report generation it would be nice to be able to save the current location as png in an HTML or PDF report. Not sure how hard this would be. 

Also it would be nice if you could make a linux-64 version on conda.

**Comment by jrobinso** [comment]
Hi, we just pushed a linux-64 version to conda.

RE the png output, that's an interesting idea but can you elaborate a bit more on how it would work?   Specifically, how would you envision the png image being returned?

**Comment by jfear** [comment]
Thank you for the quick response. 

First a little motivation. I mostly use jupyter as a lab notebook and for report generation (typically HTML) to send to collaborators. There are times during the exploratory analysis phase that you would like to sequence gaze and record regions of interest. I envision it would be nice that as I scroll around a browser track to be able to record these regions by just copying and pasting the IGV call to a new cell. 

There are two different features I would be interested in having.

1) When exporting to HTML, it would be nice to have a "live" version of the browser. This would be especially useful for sending documents to collaborators avoiding having to make UCSC genome browser tracks all of the time. (Note: this may already be possible, but I know next to nothing about javascript and could not get the browser to load in an exported html document (i.e. File -> Download as -> HTML).

2) When exporting to HTML or PDF it would be nice to have a "snapshot" of the browser view. Or in my motivation above even in a active notebook it would be nice to be able to record regions of interest.

The easiest way I can think of is to have some sort of wrapper function that could be placed around an `IGV` call and would create and return an image instead of the browser track

```
snapshot(IGV(...))
```

This would allow the user to have a "live" browser view and as they find interesting things, create a new cell and run the above snapshot and embed it in the notebook.  There are other ways I can think of using the nbconvert framework, but I this simple snapshot method would be really useful.

**Comment by jfear** [comment]
I have a quick and dirty hack incase anyone else out there is wanting to this. I tried to get this into a function, but only could get things working by using the javascript cell magic. I am sure there are better approaches, given my JS skills are 0, but it works. 

```python
%%javascript
// Converts canvas to an image
function convertCanvasToImage(canvas) 
{
    var image = canvas.toDataURL("image/png");
    return '<img src="' + image + '"/>';
}

// Grab all IGV canvas objects
var myCanvas = document.getElementsByClassName('igv-content-canvas');

// Convert each canvas and append to list
var images = [];
for (var i = 0; i < myCanvas.length; i++ )
{
    images.push(convertCanvasToImage(myCanvas[i]));
}

// combine list and output to a python object
var panel = images.join('');
IPython.notebook.kernel.execute("panel = '" + panel + "'")
```

Then run the following to display:

```python
from IPython.display import HTML
HTML(panel)
```

**Comment by jrobinso** [comment]
Thanks!

**Comment by clintval** [comment]
In case anyone is interested, modifying @jfear's code as following includes the chromosome ideogram:

```
%%javascript
// Converts canvas to an image
function convertCanvasToImage(canvas) 
{
    var image = canvas.toDataURL("image/png");
    return '<img src="' + image + '"/>';
}

// Grab all IGV canvas objects
var ideogram = document.getElementsByClassName('igv-ideogram-canvas');
var myCanvas = document.getElementsByClassName('igv-content-canvas');

// Convert each canvas and append to list
var images = [];
for (var i = 0; i < myCanvas.length; i++ )
{
    if (i == 0) {
        images.push(convertCanvasToImage(ideogram[i]));
    }
    images.push(convertCanvasToImage(myCanvas[i]));
}

// combine list and output to a python object
var panel = images.join('');
IPython.notebook.kernel.execute("panel = '" + panel + "'")
```
In Python cell:
```
from IPython.display import HTML
HTML(panel)
```
