### ISSUE TITLE
Install igv on Jupyter lab

### ISSUE THREAD

**Issue by amirshams84** [igvteam/igv-jupyter#13]
>jupyter labextension install igv
Errored, use --debug for full output:
ValueError: "igv" is not a valid extension:
No `jupyterlab` key

**Comment by jrobinso** [comment]
Thanks for the report, we don't yet support jupyter lab.   This has been a dormant project for sometime due to lack of staff, but we plan to pick it up again in the new year.    I'll leave this open and interpret it as a request to support jupyter lab.

**Comment by amirshams84** [comment]
Thanks
you are awesome by the way

Amir

**Comment by jrobinso** [comment]
Thank you very much @amirshams84.   I'm actually working on this project now and will have an update in January.  As I'm not a jupyter, or jupyter lab user I might ask for your help testing on Jupyter lab.

**Comment by jrobinso** [comment]
Hi @amirshams84 ,  after some investigation I have discovered that it is impossible, apparently, to write an extension of this type (involving javascript & python)  that works in both notebook and lab.   I'm currently focused on notebook.   I might start another project for Jupyter Lab at some point.

**Comment by amirshams84** [comment]
That would be great Jim,
Let me know when is the good time to test it on Jupyter Lab
Regards
Amir

**Comment by thondeboer** [comment]
I would also really like to be able to run KGV in JupyterLab...JupyterLab is going to be the future of Jupyter Notebooks and it would be a pity if IGV would be left behind...Is there any idea if this is going to be available? It has been a year since there was some comments about this. Which you may have interpreted as lack of interest, but for my specific use case, JupyterLab is the only option...

**Comment by jrobinso** [comment]
Hi @thondeboer yes it will be available.   Until recently there was an explicit warning to extension developers on the Jupyter site that the API was unstable and guaranteed to change.  I see they have removed that.    I will re-open this, but don't have an ETA at this time.

**Comment by jrobinso** [comment]
@thondeboer @amirshams84 I'm just not going to have time to do this but would support someone else (support in the sense of making igv.js changes if needed).   Currently I'm the primary developer for IGV Desktop, igv.js,  juicebox.js, some other projects, and this.   Just being realistic.   Anyone interested?   Its not trivial but probably easier if you work regularly in python and Jupyter (unlike myself).    In any event I'm closing this issue as the notebook extension won't work in Lab.

**Comment by cjw85** [comment]
We have a fork of igv-jupyter that now supports JupyterLab: https://github.com/epi2me-labs/igv-jupyterlab

**Comment by jrobinso** [comment]
@cjw85 Fantastic!
