### ISSUE TITLE
Various display improvement suggestions

### ISSUE THREAD

**Issue by a-slide** [igvteam/igv-jupyter#17]
Here are a few remarks and suggestions to improve the tracks display.

- The "Embedded Features" option is a great idea. Nothing to say, it is very convenient and works well.
- Bam files rendering improved a lot in the last version but for some reason displayMode = "SQUISHED" or "COLLAPSED" do not seem to work (whereas it does for vcf files)
- It would be great to have a possibility to reorder the tracks
- The track settings menu (right cog) is still a little buggy. In particular the tick is massive for the displayMode for instance.

Thanks a lot

**Comment by jrobinso** [comment]
Thanks for the feedback.   I'm aware of the cog and menu problem, also the +/- zoom buttons don't show up for me.  I think this is some CSS problem,  we'll look at it next week.

**Comment by jrobinso** [comment]
Any issues remaining here are really igv.js ones.  Closing this as there's nothing Jupyter specific.    BTW "SQUISHED" is not a supported alignment track option in igv.js,  rather you explicitly set the alignmentRowHeight to a pixel value.   A value of 1 would the equivalent of IGV desktop's squish.
