### ISSUE TITLE
Running a demo on MyBinder

### ISSUE THREAD

**Issue by psychemedia** [igvteam/igv-jupyter#20]
I was wondering if it would be possible to run the `igv.js-jupyter` demo notebooks on [MyBinder](https://mybinder.readthedocs.io/en/latest/)?

Presumably an IGV server would need to be started in the container first? (I'm new to IGV...)

**Comment by jrobinso** [comment]
I'm not familiar with MyBinder but igv.js is a pure client program, there is no server.    Its embedded in many things, that's what its designed for.

**Comment by psychemedia** [comment]
MyBinder builds and launches a Docker container based on the contents of a Github repo and particular config files specified within it ([docs](https://repo2docker.readthedocs.io/en/latest/config_files.html#config-files)), so you can provide runnable demos of a repo. The build process is sensitive to the presence of `setup.py` files and will also build / install those.

You can run this repo (and even launch into a particular notebook) here: [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/igvteam/igv.js-jupyter/master?filepath=examples%2FEmbeddedFeatures.ipynb)

One thing I noticed running the demo is that it throws an error in the browser console when I try to to `.show()` a resource, and nothing is displayed hence my question. Are there additional packages required to run the demo?

**Comment by jrobinso** [comment]
Yes,  I see an issue, not sure what it is.   I'll look into it.

**Comment by jrobinso** [comment]
@psychemedia I think you have to enable the igv extension,  pip install is not enough.   Sorry I'm a python nube and jupyter utra nube.   Try this after installing and before starting jupyter notebook
jupyter nbextension install --py igv
jupyter nbextension enable --py igv

**Comment by jrobinso** [comment]
Also, I'm not entirely clear on what the --py option does, it might not be the right thing for your environment.

**Comment by psychemedia** [comment]
Ah, yes, that could be it.

Many extensions I use are auto-installed/enabled ([howto](https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Distributing%20Jupyter%20Extensions%20as%20Python%20Packages.html#Automatically-enabling-a-server-extension-and-nbextension)) and I've got out of the habit of checking that step.

**Comment by jrobinso** [comment]
@psychemedia Thanks for that tip, I wasn't aware of that.   I build it into the next release.

**Comment by jrobinso** [comment]
@psychemedia BTW,  do you know what the "--py" flag does in those install instructions?  I can't find that documented anywhere.   --sys-prefix and --user are,  but is  "--py" neccessary and what does it do?

**Comment by jrobinso** [comment]
auto-enabling should be happening now.
