### ISSUE TITLE
Extensions enabled, but .show() .load_track() don't work

### ISSUE THREAD

**Issue by JasonJWilliamsNY** [igvteam/igv-jupyter#27]
Hope everything needed is in the screenshot. At best I get 'IGV Browser not ready'. Working on a Jupyterlab instance (JL vs. 1.0.4, python 3.7.3) inside a custom Docker container. Any clues to help me debug? 
<img width="906" alt="igv-ss" src="https://user-images.githubusercontent.com/7266775/62251003-78989580-b3bc-11e9-8a49-1dca851e37ab.png">

**Comment by jrobinso** [comment]
Hi @JasonJWilliamsNY , apologies for the delayed response.   Jupyter lab is not supported,  I would be surprised if it works as the extensions api is changed completely.   I use the term api loosely, there is not stable api published yet.

**Comment by JasonJWilliamsNY** [comment]
Thanks for your work on this and the response to the. It's such a shame and I hope they release a solution that would allow many of these valuable notebook extensions to be more easily carried over.
