### ISSUE TITLE
bam file won't display

### ISSUE THREAD

**Issue by njbernstein** [igvteam/igv-jupyter#33]
Hi there,

Trying to track down why my bam wont display, and I don't get any errors from IGV.
![Screen Shot 2020-01-27 at 11 34 00 AM](https://user-images.githubusercontent.com/6864886/73207159-16191b80-40f9-11ea-8a4b-d2a92cf0286d.png)

Nothing returns. any help would be much appreciated.

**Comment by jrobinso** [comment]
I suspect its the bam path.  If you can use Chrome or some other browser with "devtools" look at the url that path is resolving to.

**Comment by hurleyLi** [comment]
Hi,
I'm having the same problem. Everything is installed and enabled, and I got a confirmation when I launched jupyter lab `igv enabled!`. But nothing happened when I run code similar to above, and there's no error message either. Do you have any idea what might cause this?
Thanks!

**Comment by jrobinso** [comment]
Hi, first igv-jupyter does not support jupyter lab, did you mean jupyter notebook?

**Comment by njbernstein** [comment]
My issue was dumb I needed to use the full like so:
`bam_path = "http://sci-pvm-nicholas:10000/tree/projects/genomics/ukbb/ch/data/siddhartha_2017_subset_crams/5989838_23163_0_0.subset.sorted.bam"`

**Comment by jrobinso** [comment]
@njbernstein Ah ok, thanks for letting me know.  There is a way to use relative paths for files  using "file magics".   I do python so seldom the details escape me, but I did get it to work once.

**Comment by hurleyLi** [comment]
working not after switching from lab to notebook. Thanks!
