### ISSUE TITLE
How to use other fasta file as the reference

### ISSUE THREAD

**Issue by Sotdo** [igvteam/igv-jupyter#34]
Hi,

I want to know if igv-jupyter supports using other fasta file as the reference? For example, I have a customed reference file, can I use it as the reference?

If it can be done, how can I make it? 

Thanks

**Comment by jrobinso** [comment]
Use a "reference" object instead of a "genome" object during initialization.    As pointed out in the readme configuration is described in the igv.js wiki.   The reference object is described here:  https://github.com/igvteam/igv.js/wiki/Reference-Genome
