### ISSUE TITLE
Unable to Load Local Bam File

### ISSUE THREAD

**Issue by callieboskin** [igvteam/igv-jupyter#35]
Hi,
I'm unable to load local bam files with IGV-Jupyter. I'm getting an error that says Error Loading Track Data when I try to load a local bam file. The bam file path is correct, as I'm able to use the same file in a different part of the notebook with no issues. I'm able to use the same file on my local IGV app so I don't think it's the bam file itself. Additionally, I'm able to load track successfully with the external URL data from the read me (from "https://data.broadinstitute.org/igvdata/test/igv-web/segmented_data_080520.seg.gz").
Any suggestions are appreciated! 
![IGV_Jupyter_new](https://user-images.githubusercontent.com/46458373/85908258-3abd1080-b7c9-11ea-9f5c-f7aca994b01f.PNG)

![IGV_local](https://user-images.githubusercontent.com/46458373/85907989-3a704580-b7c8-11ea-832d-b47dc77d1119.png)

**Comment by jrobinso** [comment]
Important to note that igv.js is a webapp so the path must be a URL, not a file path.     The path you entered above will be converted to a URL by the browser,  to see what the URL is open developer tools in chrome and look at the "network" tab.  

If you are trying to serve this file from the jupyter server you can use something called "files" magic.   I'm not a python expert but our example notebooks use this trick.   You can examine them.

If the path isn't the problem look in the console (from developer tools) for error messages.

**Comment by callieboskin** [comment]
I'll try that! Thanks for the quick response!

**Comment by edwwlui** [comment]
softlink can be used as a workaround
