### ISSUE TITLE
Feature Request: Support for JupyterLab

### ISSUE THREAD

**Issue by jonn-smith** [igvteam/igv-jupyter#38]
The current extensions seem to be for JupyterNotebooks only.  Can you update this codebase to work with JupyterLab as well?

It may be relatively easy - I haven't looked into it myself.  I just know that jupyter notebook extensions are not compatible with jupyter lab.

**Comment by jrobinso** [comment]
Hi @jonn-smith, Its actually not easy, it will be a major rewrite, and we on the IGV team do not have resources to pursue this.    There are 2 extensions involved, a client and server (python) extension.

**Comment by mmreich** [comment]
The GenePattern Notebook project, http://notebook.genepattern.org, will be implementing igv.js as a launchable tool within JupyterLab, as part of a collection of bioinformatics tools we're incorporating into the Jupyter architecture. As development progresses, we'll post about this on the @GenePattern twitter account.

**Comment by tmtabor** [comment]
With the latest release, support had now been added for JupyterLab 3.x.

**Comment by jonn-smith** [comment]
Excellent!  I'm not sure when, but hopefully soon I'll try it out.
