### ISSUE TITLE
"Error accessing resource: presigned url Status:0" when trying to load presigned url to igv-jupyter

### ISSUE THREAD

**Issue by JoannaTan** [igvteam/igv-jupyter#42]
Hi,

I am trying to load my VCF from a private S3 bucket. 
I generated a presigned URL and tried to load to igv-jupyter but i kept getting the following message:
"Error accessing resource: presigned url Status:0"

I tried to load the presigned url to IGV on my windows desktop and it works fine. This indicates that the presigned url is working fine.

Is there anything that I need to set in order for igv-jupyter to work with presigned url?

I am using
jupyter notebook version: 6.1.4
python version: 3.7.9
igv-jupyter version: 0.9.8

**Comment by tmtabor** [comment]
It's worth checking the response headers coming from S3. If there is no "Access-Control-Allow-Origin" header in the response, this may be a CORS issue. If that's the case, you'll need to [modify your AWS S3 config](https://aws.amazon.com/blogs/media/deep-dive-into-cors-configs-on-aws-s3-how-to/).

**Comment by JoannaTan** [comment]
Thank you. I edit the CORS config and it works now.
