### ISSUE TITLE
Problems loading GTF file

### ISSUE THREAD

**Issue by sagnikbanerjee15** [igvteam/igv-jupyter#48]
Hello,

I am using the following code to load a gtf file but nothing gets loaded. Could you please look into it?

```
track_list = [
            {
                "name": "HA",
                "url": "HA.gtf",
                "format": "gff",
                "type": "annotation",
                "indexed": False
            }
        ]

b = igv.Browser( 
    {"reference": {
        "id": "ref",
        "fastaURL": "genome.fasta",
        "indexed": False,
        "tracks": track_list
    }}
 )

b.show()
```

![image](https://user-images.githubusercontent.com/23457977/149674931-bd426661-5415-4b66-855c-4237948ea603.png)

But once I load it manually, I can see the features

![image](https://user-images.githubusercontent.com/23457977/149674950-b6a3b3c8-58fc-4ea9-825d-060c3ebc4e70.png)

Thank you.

**Comment by sagnikbanerjee15** [comment]
I figured the error. The gtf file was empty.

**Comment by jrobinso** [comment]
Also, if it's a gtf file the format should be "gtf",  not "gff".
